#!/usr/bin/env node
// Credential discovery + .env.local writer for the 医保可信数据通行 Agent.
// Discovery order (PRD 12.2): project .env.local / .dev.vars / .env ->
// ~/user_key.txt -> ~/use_key.txt. Never prints secret values.
// Usage: node scripts/apply_use_key_env.mjs [--dry-run]

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const DRY = process.argv.includes("--dry-run");
const PROJECT = process.cwd();
const HOME = homedir();

const SOURCES = [
  join(PROJECT, ".env.local"),
  join(PROJECT, ".dev.vars"),
  join(PROJECT, ".env"),
  join(HOME, "user_key.txt"),
  join(HOME, "use_key.txt"),
];

function parseEnv(path) {
  const out = {};
  try {
    for (const raw of readFileSync(path, "utf8").split(/\r?\n/)) {
      const line = raw.trim();
      if (!line || line.startsWith("#")) continue;
      const eq = line.indexOf("=");
      if (eq === -1) continue;
      const k = line.slice(0, eq).trim();
      let v = line.slice(eq + 1).trim();
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1);
      }
      if (k) out[k] = v;
    }
  } catch {
    /* ignore */
  }
  return out;
}

function pickModel(env) {
  return (
    env.OPENAI_MODEL ||
    env.OPENAI_DEFAULT_MODEL ||
    env.OPENAI_MODEL_DEFAULT ||
    env.OPENAI_MODEL_REASONING ||
    ""
  );
}

let found = null;
let source = null;
for (const path of SOURCES) {
  if (!existsSync(path)) {
    console.log(`  miss   ${path.replace(HOME, "~")}`);
    continue;
  }
  const env = parseEnv(path);
  if (env.OPENAI_API_KEY && pickModel(env)) {
    found = env;
    source = path;
    console.log(`  FOUND  ${path.replace(HOME, "~")}  (OPENAI_API_KEY + model)`);
    break;
  }
  console.log(`  exists ${path.replace(HOME, "~")}  (no usable OPENAI_* pair)`);
}

if (!found) {
  console.error("\n[apply_use_key_env] 未发现可用 provider 凭证。P0 将进入降级模式。");
  process.exit(2);
}

const apiKey = found.OPENAI_API_KEY;
const baseUrl = found.OPENAI_BASE_URL || "https://api.openai.com/v1";
const model = pickModel(found);
let host = baseUrl;
try {
  host = new URL(baseUrl).host;
} catch {
  /* keep raw */
}

console.log("\n[apply_use_key_env] 凭证摘要（不打印明文）：");
console.log(`  source : ${source.replace(HOME, "~")}`);
console.log(`  host   : ${host}`);
console.log(`  model  : ${model}`);
console.log(`  apiKey : ****${apiKey.slice(-4)} (len=${apiKey.length})`);

if (DRY) {
  console.log("\n[dry-run] 未写入 .env.local。");
  process.exit(0);
}

const target = join(PROJECT, ".env.local");
const body = `# Auto-generated by scripts/apply_use_key_env.mjs — DO NOT COMMIT.
# Source: ${source.replace(HOME, "~")}
OPENAI_API_KEY=${apiKey}
OPENAI_BASE_URL=${baseUrl}
OPENAI_MODEL=${model}
`;
writeFileSync(target, body, { mode: 0o600 });
console.log(`\n[apply_use_key_env] 已写入 ${target.replace(HOME, "~")} (chmod 600)。`);
